nginx:
    image: nginx
    ports:
        - "8080:80"
    links:
        - phpfpm
    volumes:
        - ./nginx:/etc/nginx/conf.d/

        - ./logs/nginx-error.log:/var/log/nginx/error.log
        - ./logs/nginx-access.log:/var/log/nginx/access.log

        - ./public:/var/www/html

phpfpm:
    image: kunalgautam/phpfpm
    ports:
        - "9000:9000"
    volumes:
        - ./public:/var/www/html
    links:
        - mysql
mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: admin
  volumes:
      - "./mariadb:/var/lib/mysql:rw"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql
  ports:
    - 8181:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: admin
    PMA_ARBITRARY: 1
    PMA_HOST: mysql

