version: '2'
services: 
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - "./public_html:/var/www/html:rw"
      - "./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini"

    links:
      - mysql:mysql

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - "./mariadb:/var/lib/mysql:rw"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ARBITRARY: 1
      PMA_HOST: mysql